### ISSUE TITLE
tabixpp build issue

### ISSUE THREAD

**Issue by alimanfoo** [vcflib/vcflib#11]
Hi Erik, could you update the tabixpp submodule, I see you fixed the libz build issue in the tabixpp repo but vcflib still points to an older tabixpp commit and so vcflib won't make on Ubuntu.

**Comment by avilella** [comment]
This looks like the same Issue I am having trying to compile on Ubuntu:

gcc -g -Wall -O2 -fPIC  -o tabix main.o -lm  -lz -L. -ltabix
./libtabix.a(bgzf.o): In function `deflate_block':
/home/avilella/src/vcflib/tabixpp/bgzf.c:311: undefined reference to`deflate'
/home/avilella/src/vcflib/tabixpp/bgzf.c:313: undefined reference to `deflateEnd'
/home/avilella/src/vcflib/tabixpp/bgzf.c:305: undefined reference to`deflateInit2_'
/home/avilella/src/vcflib/tabixpp/bgzf.c:329: undefined reference to `deflateEnd'
/home/avilella/src/vcflib/tabixpp/bgzf.c:345: undefined reference to`crc32'
/home/avilella/src/vcflib/tabixpp/bgzf.c:346: undefined reference to `crc32'
./libtabix.a(bgzf.o): In function`inflate_block':
/home/avilella/src/vcflib/tabixpp/bgzf.c:380: undefined reference to `inflateInit2_'
/home/avilella/src/vcflib/tabixpp/bgzf.c:385: undefined reference to`inflate'
/home/avilella/src/vcflib/tabixpp/bgzf.c:391: undefined reference to `inflateEnd'
/home/avilella/src/vcflib/tabixpp/bgzf.c:387: undefined reference to`inflateEnd'
./libtabix.a(bedidx.o): In function `ks_getuntil':
/home/avilella/src/vcflib/tabixpp/bedidx.c:11: undefined reference to`gzread'
./libtabix.a(bedidx.o): In function `bed_read':
/home/avilella/src/vcflib/tabixpp/bedidx.c:103: undefined reference to`gzdopen'
./libtabix.a(bedidx.o): In function `ks_getc':
/home/avilella/src/vcflib/tabixpp/bedidx.c:11: undefined reference to`gzread'
./libtabix.a(bedidx.o): In function `bed_read':
/home/avilella/src/vcflib/tabixpp/bedidx.c:138: undefined reference to`gzclose'
/home/avilella/src/vcflib/tabixpp/bedidx.c:103: undefined reference to `gzopen64'
collect2: ld returned 1 exit status
make[2]: *** [tabix] Error 1
make[2]: g++ -O3 -D_FILE_OFFSET_BITS=64   -c -o smithwaterman/IndelAllele.o smithwaterman/IndelAllele.cpp
*** Waiting for unfinished jobs....
make[2]: Leaving directory`/home/avilella/src/vcflib/tabixpp'
make[1]: **\* [all-recur] Error 1
make[1]: Leaving directory `/home/avilella/src/vcflib/tabixpp'
make: *** [tabixpp/tabix.o] Error 2
make: *** Waiting for unfinished jobs....
make[1]: Leaving directory`/home/avilella/src/vcflib/fastahack'

**Comment by ekg** [comment]
This should resolve the issue, please let me know if it does not.

**Comment by zamiqbal** [comment]
Erik - I've just pulled, and the issue is still there for me...
